spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testbootcamp?serverTimezone=Europe/Minsk&useSSL=false
    username: root
    password: mysql13

  jpa:
    properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    show-sql=true
    open-in-view=true
    hibernate.ddl-auto=none

server:
  port: 8083